version: '3.8'

services:
  votingly-db:
    container_name: votingly-db
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=votingly

volumes:
  pgdata:
