#
# DB
spring.datasource.url=jdbc:postgresql://votingly-db:5432/votingly
# spring.datasource.platform=postgres
spring.datasource.username=postgres
spring.datasource.password=1234
# spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.data-locations=classpath:data.sql
