############################################################################################################
################## CONFIG FOR LOCAL DEVELOPMENT ENVIRONMENT ################################################
############################################################################################################
# DB
spring.datasource.url=jdbc:postgresql://localhost:5431/votingly
spring.datasource.username=postgres
spring.datasource.password=1234
spring.sql.init.data-locations=classpath:/sql/data.sql