version: '3.8'

services:
  # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
  # (Adding the "ports" property to this file will not forward from a Codespace.)

  # Dev Container
  votingly:
    container_name: votingly
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    # restart: always
    volumes:
      - .:/workspace:cached
      - ${HOME}y/.ssh:/home/vscode/.ssh
    environment:
      - SPRING_PROFILES_ACTIVE=devcontainer
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    expose:
      - "8082"
    ports:
      - "8082:8080"

  # phpMyAdmin database manager
  # votingly-adminer:
  #   container_name: votingly-adminer
  #   image: dockette/adminer:full
  #   restart: always
  #   expose:
  #     - "8282"
  #   ports:
  #     - "8282:80"

